### ISSUE TITLE
Researching ALLi Competitors from Directory

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#10]
Please look at the ALLi website and make a list of all other competitors (not editorial) please

https://www.allianceindependentauthors.org/

**Comment by ghost** [comment]
Completed 14/08/2024
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={ab74ced5-6494-4b80-8630-3e96dd41ab0c}&action=edit
