### ISSUE TITLE
Contact All Internal Authors

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#17]
Look through all internal authors and make a list of those who haven’t been contacted recently.
Draft an email to authors asking them to engage with M&A

**Comment by Hattieb101** [comment]
List of authors has been made and a draft email has been made and sent to Lucy and Cat. Waiting for the feedback then will email it out

**Comment by Hattieb101** [comment]
does this still need to be completed?
