### ISSUE TITLE
UK Uni Database Updating

### ISSUE THREAD

**Issue by CatCharlton** [LucyJonesRV/Marketing-Researchers#23]
https://www.loom.com/share/b961153354294899a00c5c4ce954ba8d?sid=56b71d6b-e949-4981-900d-8f312d2c692a

https://www.loom.com/share/f3d442af85524aed8ac3b25fe2366182?sid=79086926-aee3-4a56-9b9c-1a04ce1a0217

You then need to go to Podio (http://www.podio.com/) and login with the following:
info@rowanvalebooks.com
Podio2019!

**Comment by LucyJonesRV** [comment]
Pippa emailed recruitment with list and queried if they need any further info
