### ISSUE TITLE
Research into Rowanwood Writing

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#40]
Email in MR inbox from PubAd Team 16.10.23. Please complete full analysis on the competitor and upload onto the OD. Instructions can be found here: @marketing Team > RVM (Rowanvale Marketing) > SMAs > Competitor Research > Analysis Steps.

Please open the 'Process for Analysis' doc and follow the steps, including the other documents mentioned in the instructions.

Any questions, please email me! :)

**Comment by ghost** [comment]
Completed 08/08/2024
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={85476f9d-3012-4414-a8af-bafdb53f6f8c}&action=edit
