### ISSUE TITLE
Get Your Self-Pub Questions Answered

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#49]
https://www.youtube.com/watch?v=RYbVZneYOGs&ab_channel=AllianceofIndependentAuthors

Please make notes and save off in the OD > Marketing Researchers folder

**Comment by ghost** [comment]
I just checked the Market Researchers folder and it appears that this has already been done as there is a document in there about this video
https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7BA6F74720-E06C-4B90-AA0F-D852F92E0B8A%7D&file=Get%20Your%20Self-Publishing%20Questions%20Answered.odt&action=default&mobileredirect=true
https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B10169722-3D64-40FC-A01E-02BAE0975676%7D&file=Get%20Your%20Self-Pub%20Questions%20Answered%20podcast%20note.docx&action=default&mobileredirect=true
