### ISSUE TITLE
Competitor Research Analysis - Softwood Books

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#51]
Email in MR inbox from PubAd Team 16.10.23. Please complete full analysis on the competitor and upload onto the OD. Instructions can be found here: https://github.com/marketing Team > RVM (Rowanvale Marketing) > SMAs > Competitor Research > Analysis Steps.

Please open the 'Process for Analysis' doc and follow the steps, including the other documents mentioned in the instructions.

Any questions, please email me! :)

**Comment by ghost** [comment]
Completed 08/08/2024
https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B94E13578-D46D-411C-8897-573F2170B1FE%7D&file=Competitor%20Research%20Analysis%20-%20Softwood%20Books.docx&action=default&mobileredirect=true
