### ISSUE TITLE
Competitor Research Analysis - PR for Books 

### ISSUE THREAD

**Issue by CatCharlton** [LucyJonesRV/Marketing-Researchers#59]
Email in MR inbox from AccMan Team 11.06.24. Please complete full analysis on the competitor and upload onto the OD. Instructions can be found here: Marketing Team > RVM (Rowanvale Marketing) > SMAs > Competitor Research > Analysis Steps.

Please open the 'Process for Analysis' doc and follow the steps, including the other documents mentioned in the instructions.

**Comment by PippaSeager** [comment]
https://docs.google.com/document/d/1ejSIslJH9kMElmAAB1EeUdnVVfgb4H9ENpxiIvmO2Eo/edit

**Comment by ghost** [comment]
Completed 07/08/2014:
https://rowanvalebooks-my.sharepoint.com/:w:/g/personal/sarah_rowanvalebooks_onmicrosoft_com/Eb1aRS5om01LiTPqOdMmvXcBw6RCyxEkQO0Fjd_7AmSuuQ?e=vehupg
