### ISSUE TITLE
Competitor Research Analysis - White Magic Studios

### ISSUE THREAD

**Issue by CatCharlton** [LucyJonesRV/Marketing-Researchers#60]
Email in MR inbox from PubAd Team 19.06.24. Please complete full analysis on the competitor and upload onto the OD. Instructions can be found here: Marketing Team > RVM (Rowanvale Marketing) > SMAs > Competitor Research > Analysis Steps.

Please open the 'Process for Analysis' doc and follow the steps, including the other documents mentioned in the instructions.

**Comment by PippaSeager** [comment]
https://docs.google.com/document/d/1krK-rVYYqbDkgyBQjMKMnHBeckRfqyNmJh9I3gajXRg/edit

**Comment by PippaSeager** [comment]
https://rowanvalebooks-my.sharepoint.com/:w:/g/personal/sarah_rowanvalebooks_onmicrosoft_com/EYI3hFofn5ZGlEcAPCUr6o0BtGbDZYZHADDJapWyh6f2-g?e=HZQqmp
I have converted the analysis to a word doc

**Comment by ghost** [comment]
Completed 07/08/2024:
https://rowanvalebooks-my.sharepoint.com/:w:/g/personal/sarah_rowanvalebooks_onmicrosoft_com/EdnGLTAeMTlCl70IIFV4SDEBdL4lsAiK3BeGsgSoVC6gWg?e=IGnxdj
