### ISSUE TITLE
Competitor Research Analysis - Trafford Publishing

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#62]
Email in MR inbox from PubAd Team 17.07.24. Please complete full analysis on the competitor and upload onto the OD. Instructions can be found here: Marketing Team > RVM (Rowanvale Marketing) > SMAs > Competitor Research > Analysis Steps.

Please open the 'Process for Analysis' doc and follow the steps, including the other documents mentioned in the instructions.

**Comment by ghost** [comment]
https://docs.google.com/document/d/1eC-6Xo75g657WE_Mv2n28U-EZq24JKDAN37Fw9o1Wks/edit

**Comment by ghost** [comment]
Completed 07/08/2024:
https://rowanvalebooks-my.sharepoint.com/:w:/g/personal/sarah_rowanvalebooks_onmicrosoft_com/EYI3hFofn5ZGlEcAPCUr6o0BtGbDZYZHADDJapWyh6f2-g?e=HZQqmp
I have converted the analysis to a word doc
