### ISSUE TITLE
Competitor Research Analysis - YourPaperQuest

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#63]
Email in MR inbox from AccMan Team 12.08.24. Please complete full analysis on the competitor and upload onto the OD. Instructions can be found here: https://github.com/marketing Team > RVM (Rowanvale Marketing) > SMAs > Competitor Research > Analysis Steps.

Please open the 'Process for Analysis' doc and follow the steps, including the other documents mentioned in the instructions.

Any questions, please email me! :)

**Author email**
_They operate a subscriber system for Readers to buy into ( @£18 per month) and promote Indie Authors, like me, who could earn from being a chosen publication.
This would, potentially, be a complementary revenue stream ( similar to one of the Amazon schemes for e-book ).

What are your/Rowanvales' thoughts on this avenue?
Are there any issues with this?_

**Comment by ghost** [comment]
Competed 13/08/2024:
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={dff6861b-4b0a-4597-9e48-751f48c00bd5}&action=edit
