### ISSUE TITLE
Competitor Research Analysis - LR Price Publications

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#65]
Email from PubAd team in MR inbox 21/08/24.

Please complete full analysis on the competitor and upload onto the OD. Instructions can be found here: https://github.com/marketing Team > RVM (Rowanvale Marketing) > SMAs > Competitor Research > Analysis Steps.

Please open the 'Process for Analysis' doc and follow the steps, including the other documents mentioned in the instructions.

_We have an author who is looking to publish with us following issues with their previous publisher, LR Price Publications. They have mentioned various issues with them, and it sounds like the company might be going under shortly. However, Cat C has recommended that, as a result, we might be able to swoop in and work with some of their dissatisfied authors, if we are able to research a bit more into them and find authors who are (or were planning to) working with them._

**Comment by ghost** [comment]
Completed 22/08/2024
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={ce273e24-5aaa-493d-9bdb-db94e48eb6c0}&action=edit
