### ISSUE TITLE
Blog post research - Revive book sales

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#68]
Read and summarise article. Save summary to MRs research & forward to Yol anything you think may be useful for M&A service development

https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fsarah%5Frowanvalebooks%5Fonmicrosoft%5Fcom%2FDocuments%2F%40%20Marketing%20Team%2FMarketing%20Researchers%2FMR%27s%20Research

https://kindlepreneur.com/revive-dead-book/

**Comment by IndieRT** [comment]
Completed 10.09.24
https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7BEBC13779-BA79-4178-89FF-7C7522EEF754%7D&file=How%20to%20revive%20dead%20book%20sales%20summary%20notes.docx&action=default&mobileredirect=true
