### ISSUE TITLE
Blog post research - Kindle rankings PDF 

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#69]
Read through and summarise the eBook. Save to MR research folder.

Send to Yol if any information is useful to developing our M&A service 

[https://kindlepreneur.com/wp-content/uploads/2024/08/The-Authors-Guide-to-Amazon-Visibility-Kindlepreneur-EBook.pdf](https://click.convertkit-mail.com/qdu6rwpgkwu7h7keq26cqi8kgzkkkc9zwgkq849qvn0kk03d78ggv9q7wg0q8gvvpve8v39p63v5d3dpe6qg0r67mpn26zg0zzp3l80mq5lo8oz27xrkre00w9g/e0hph0u0orex65h7/aHR0cHM6Ly9raW5kbGVwcmVuZXVyLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAyNC8wOC9UaGUtQXV0aG9ycy1HdWlkZS10by1BbWF6b24tVmlzaWJpbGl0eS1LaW5kbGVwcmVuZXVyLUVCb29rLnBkZg==)

**Comment by IndieRT** [comment]
Completed 10/09/2
https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7BCB312DE7-B0F7-494F-A07D-CC2468EEFE83%7D&file=Kindle%20eBook%20summary%20notes.docx&action=default&mobileredirect=true
