### ISSUE TITLE
Watch video on Amazon Ads

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#70]
Make notes on video - forward anything important to Yol. Save summarised note to MR research folder on OD 

[https://www.youtube.com/watch?v=SsMxmf62_PY](https://click.convertkit-mail.com/27uvv4mlv2aohvkz8mxu3hroon344ug/z2hgh7u36mdzv9fz/aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1Tc014bWY2Ml9QWQ==)

**Comment by IndieRT** [comment]
https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B6558AC14-F57B-4844-9928-2C028660C7BA%7D&file=Amazon%20Ads%20Vide%20Summary%20Notes.docx&action=default&mobileredirect=true

**Comment by IndieRT** [comment]
Completed on 09/09/24
