### ISSUE TITLE
Summarise What's New with Amazon Ads email

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#71]
Email in MR inbox 27th August forwarded from Yolanda

Summarise and save notes onto OD

**Comment by ghost** [comment]
https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B1CBA0D9C-9F04-4DF7-8CFF-85F20BFC21DE%7D&file=‘What’s%20new%20with%20Amazon%20Ads’%20–%20Email%20Summary.docx&action=default&mobileredirect=true
