### ISSUE TITLE
Competitor Analysis - Go through list in link 

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#72]
https://peoplesbookprize.com/publishers/ - check which of the publishers listed on there are competitors (therefore competitor analysis should be completed for them) or independent traditional publishers.

**Comment by ghost** [comment]
Completed 28/08/2024:
UK-based direct competitors:

Austin Macauley 
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={93f6d113-d6cf-4296-a1eb-56a84aae1dd3}&action=edit

Black and White Publishing
https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7BA206FE78-E8C1-4D97-B0A3-8928C245739A%7D&file=Competitor%20Research%20Analysis%20-%20Black%20and%20White%20Publishing.docx&action=default&mobileredirect=true

Blossom Spring Publishing
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={2a1c09ba-b5b5-493e-a824-f7313f4950e7}&action=edit

Boldwood Books
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={a7bec05d-5939-435e-ba7d-0ad014fc91e9}&action=edit

Cranachan Publishing
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={cab12fc4-c19e-4c76-a9e3-80dd508573d2}&action=edit

**Comment by ghost** [comment]
Completed 05/09/2024:
Uk-based direct competitors:

Darf Publishing:
https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7BC08CEE56-2BFD-4A2C-AC59-302924CA543B%7D&file=Competitor%20Research%20Analysis%20-%20Darf%20Publishing.docx&action=default&mobileredirect=true

Fairlight Books:
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={aab3db00-0024-4276-94de-b69130f7c40d}&action=edit

Filament Publishing:
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={652c6695-8293-466e-a8ef-be5ab309b396}&action=edit

**Comment by ghost** [comment]
Completed 09/09/2024:
UK-based direct competitors:

Gallic Books:
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={1bcb6a4e-c738-4d90-9344-259488c7d17b}&action=edit

Hammersmith Books:
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={3dc43e71-1274-4907-835c-e79e3bcf4d60}&action=edit

**Comment by ghost** [comment]
Completed 13/09/2024:
UK-based direct competitors:

Hashtag Press:
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={93fb927a-f28c-4155-9835-3cf322d3495a}&action=edit

Hikari Press:
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={c0060f1c-d6e9-472e-a97d-e1d756d88f68}&action=edit

IndieBooks:
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={8ea750fa-15b5-4f81-b3e6-f27f8dda119d}&action=edit

JellyBean Self-publishing:
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={dbd1e4e3-3a0f-400d-bba6-b72cffbf0162}&action=edit

**Comment by ghost** [comment]
Completed 14/09/2024:
UK-based direct competitors:

Jessica Kingsley Publishers:
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={e2833a44-cc5d-460a-8ed7-ac56cc280f7c}&action=edit

Joffe Books:
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={78f31802-5c5e-4b76-a53b-b9123efe27d3}&action=edit
