### ISSUE TITLE
Research and summary notes - Giveaways

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#74]
Read through document and make summary notes - Save to MR research folder on OD if useful. Send any useful information on developing M&A service to Yol 
 [https://docs.google.com/document/d/1I_LpeR9dJ9VrZs4aTMHbWKK35dB9LIUU0iVZkkUqyYc/edit?usp=sharing](https://click.convertkit-mail.com/4zun32xkk4ueh5xm66dhxh679e777s5/owhkhqhrd9969qiv/aHR0cHM6Ly9kb2NzLmdvb2dsZS5jb20vZG9jdW1lbnQvZC8xSV9McGVSOWRKOVZyWnM0YVRNSGJXS0szNWRCOUxJVVUwaVZaa2tVcXlZYy9lZGl0P3VzcD1zaGFyaW5n)

**Comment by IndieRT** [comment]
https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B4E0D0813-EFFC-4EC7-A380-D892318537D6%7D&file=500%20New%20Fans%20Summary%20Notes.docx&action=default&mobileredirect=true

**Comment by IndieRT** [comment]
Completed 9/09/24
