### ISSUE TITLE
Organise MR Research Folder

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#75]
1. Organise the Mr's Research folder [MR's Research - OneDrive (sharepoint.com)](https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fsarah%5Frowanvalebooks%5Fonmicrosoft%5Fcom%2FDocuments%2F%40%20Marketing%20Team%2FMarketing%20Researchers%2FMR%27s%20Research) Create subfolders and move the relevant documents into them.

E.g. Mark Dawson Course, Nick Stephenson Course, Kindlepreneur, Amazon Ads etc

2. Create a summary word document for all folders you create. (You will need to skim through each document) Summarise what is included in the documents - bullet point any important information and highlight anything that is still relevant and can be implemented into our M&A team. Anything you think that needs to be implemented please check and see if it is in the relevant M&A guide. Anything that you think could be a Blog Post idea, make a note of (Blog post idea and location of document) and forward in a list to Yol. 
3. Send over the summary document to Yol to check over & save summary document to the relevant folder 

Any questions, let me know! 

https://www.loom.com/share/57faaf1aaab44af5add24be21e55efcf

**Comment by IndieRT** [comment]
Completed 23/9/24
https://rowanvalebooks-my.sharepoint.com/shared?id=%2Fpersonal%2Fsarah%5Frowanvalebooks%5Fonmicrosoft%5Fcom%2FDocuments%2F%40%20Marketing%20Team%2FMarketing%20Researchers%2FMR%27s%20Research&listurl=%2Fpersonal%2Fsarah%5Frowanvalebooks%5Fonmicrosoft%5Fcom%2FDocuments
