### ISSUE TITLE
Read and Summarise Amazon's New Identity Verification document

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#76]
Read through document and summarise in a Word doc - save to MR Research folder 

​[https://kindlepreneur.com/how-to-choose-a-pen-name/](https://click.convertkit-mail.com/k0uvdg9p7gb6hdogdnwbxio7ed277f04e26zq80zwvl66ln7rq22w0zre2lzq2wwxwkqwn0xgnwm7n7xkgz2l3gr9xvdg42l44xn5ql9zm5pqp4dro363klle02/l2heh6u39o2xe2hg/aHR0cHM6Ly9raW5kbGVwcmVuZXVyLmNvbS9ob3ctdG8tY2hvb3NlLWEtcGVuLW5hbWUv)

**Comment by ghost** [comment]
https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B7279DB6D-3E6A-4CF3-B7EB-133226E8C761%7D&file=Amazon%20New%20identity%20verification%20document%20summary.docx&action=default&mobileredirect=true
