### ISSUE TITLE
Read and Summarise the Article "How to Choose a Pen Name" 

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#77]
Read and summarise article - Save Word doc summary to [Blog Post Ideas - OneDrive (sharepoint.com)](https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fsarah%5Frowanvalebooks%5Fonmicrosoft%5Fcom%2FDocuments%2F%40%20Marketing%20Team%2FMarketing%20Researchers%2FMR%27s%20Research%2FBlog%20Post%20Ideas)

https://kindlepreneur.com/how-to-choose-a-pen-name/?ck_subscriber_id=802550112&utm_source=convertkit&utm_medium=email&utm_campaign=[Important]:%20Amazon%27s%20New%20Identity%20Verification%20-%2014930727&sh_kit=ccc5b5c9c339d93a30f561f99b0d787989c02eb334c7a9d66d7ded32730d911e

**Comment by IndieRT** [comment]
Completed 28/10/24
https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7BFCF10727-38B3-461D-BC27-5D8B9C25D588%7D&file=How%20to%20Choose%20a%20Pen%20Name%20in%202024.docx&action=default&mobileredirect=true
