### ISSUE TITLE
Read and Summarise article on Building a Platform 

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#79]
Read and summarise the article [https://insights.bookbub.com/building-author-platform/](https://click.convertkit-mail.com/wvu7d3pggxigh5l4w3gs7hnx859xxs8/reh8hoh0rxwedxc2/aHR0cHM6Ly9pbnNpZ2h0cy5ib29rYnViLmNvbS9idWlsZGluZy1hdXRob3ItcGxhdGZvcm0v)

Save Word Doc to MR Research folder & send summary to Yol

**Comment by IndieRT** [comment]
Completed 24/10/24
https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7Ba4f060ad-7794-42c0-b12c-e518f46f5a94%7D&action=edit&wdPid=5be2e395
