### ISSUE TITLE
Watch and Summarise

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#80]
Watch Dave at Kindlepreneur video on Is Amazon Hiding Your Book? - make relevant notes and add any useful information to the M&A Service handbook (make sure you follow the instructions on adding info to the handbook please) and send in an email to Yol anything you think might be important 

[M&A Service Handbook & Templates.docx (sharepoint.com)](https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7BD22F12DA-FCC8-4DEE-925D-E9EB129C4DBF%7D&file=M%26A%20Service%20Handbook%20%26%20Templates.docx&action=default&mobileredirect=true)

[https://www.youtube.com/watch?v=S_uuzBTXTSA](https://click.convertkit-mail.com/4zu2p6den6ieh5xzz7qfmi679e777s5/6qhehou7e630ens9/aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1TX3V1ekJUWFRTQQ==)

**Comment by IndieRT** [comment]
Completed 24/10/24
https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7BA58468E6-0368-4075-B851-EE52E3ACCA5D%7D&file=Is%20Amazon%20Hiding%20Your%20Book.docx&action=default&mobileredirect=true
