### ISSUE TITLE
Watch and Summarise

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#81]
Watch Dave at Kindlepreneur video on Amazon Shutting down KDP accounts – make relevant notes and add any useful information to the M&A Service handbook (make sure you follow the instructions on adding info to the handbook please) and send in an email to Yol anything you think might be important 

[M&A Service Handbook & Templates.docx (sharepoint.com)](https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7BD22F12DA-FCC8-4DEE-925D-E9EB129C4DBF%7D&file=M%26A%20Service%20Handbook%20%26%20Templates.docx&action=default&mobileredirect=true)

[www.youtube.com/watch?v=FO1c1YPrzEE](https://click.convertkit-mail.com/lmu0n6dpo6umh0m8qqxi3idom6600fg/qvh8h8urzlvqpkbg/aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1GTzFjMVlQcnpFRQ==)

**Comment by IndieRT** [comment]
Completed 22/10/24
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={0dfd1807-2c7c-44bc-b7c5-f2bbb388b97f}&action=edit
