### ISSUE TITLE
VERY URGENT - Ensure published books are showing

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#83]
Please go through and check Nielsen Title Editor vs Athena vs our website to ensure all our published books are showing on each one. Logins for Nielsen and Athena are below.

</pre>
</body>
</html>Task video =  https://www.loom.com/share/b5bd364d7b3c4f8284c5fe2a88f9c3b0?sid=f7904a75-4375-480e-ae54-1d519fafbf13

Logins =
Nielsen Title Editor
ROWANVPW
fyrtu2-xomnub-Bevcem
Athena
https://rowanvale-athena.netlify.app/
[info@rowanvalebooks.com](mailto:info@rowanvalebooks.com)
aS2miTHq5cW892N

Please use the spreadsheet that Cat has created for discrepancies that you find, which is saved off here = [Athena Nielsen Book Store.xlsx](https://rowanvalebooks-my.sharepoint.com/:x:/g/personal/sarah_rowanvalebooks_onmicrosoft_com/EZCwmHi1PB5KkX1HQkhlLWoBGzJxdQTE9G4AG73vwSUIhQ?e=tFFRnG)

Please edit the s/sheet without downloading it (either clicking into it or click Open in App) so that you are all working from the same version. 

If you need help with this task, please email CatC directly and she will assist.

One person is to start from newest to oldest and fill in from the top of the s/sheet and another person to fill in from oldest to newest at the bottom of the s/sheet. Any discrepancies/info missing should be put in RED font.

**Comment by IndieRT** [comment]
Completed 16/10/24
