### ISSUE TITLE
Watch "Want to Know What Keywords a Book Uses?" Video and Summarise

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#84]
Watch video and make summary notes on a Word Doc

[youtube.com/watch?v=0wLeamxNr6U](https://click.convertkit-mail.com/k0uvdg9p7gb6hdonmwrcxio7ed277f04e26zq80zwvl66ln7rq22w0zre2lzq2wwxwkqwn0xgnwm7n7xkgz2l3gr9xvdg42l44xn5ql9zm5pqp4dro363klle02/kkhmh2ulq0p2w8uk/aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj0wd0xlYW14TnI2VQ==)

Save notes to MR Research folder [MR's Research - OneDrive (sharepoint.com)](https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fsarah%5Frowanvalebooks%5Fonmicrosoft%5Fcom%2FDocuments%2F%40%20Marketing%20Team%2FMarketing%20Researchers%2FMR%27s%20Research)

**Comment by IndieRT** [comment]
Completed 22/10/24
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={2bd02318-182a-4596-936c-82fb008548d6}&action=edit
