### ISSUE TITLE
Watch Amazon Ads video training and summarise

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#85]
Watch the training video and make summary notes on a Word Doc - save the summary to the MR Research folder [MR's Research - OneDrive (sharepoint.com)](https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fsarah%5Frowanvalebooks%5Fonmicrosoft%5Fcom%2FDocuments%2F%40%20Marketing%20Team%2FMarketing%20Researchers%2FMR%27s%20Research)

In case you missed it, or want to see it again, here's the link to watch the recording of the Amazon Ads Workshop where I review 5 author's Amazon Ads and show you how to fix common problems.

[Replay link](https://xn380.keap-link001.com/v2/click/c1c863cd5d0c74c8971e05d465852879/eJyNkMtuwjAQRf9l1gl5gBB4hxBCUYAFatfVKBmDFce27OGRovx7TVWxaqVu5545ozsPYDJouGpBwN1MFzkk4KlRTpHhtTWMzXc4nS3neQJamW7r7cWBePy2-sqf07Io8zIBHhxF5O24WtfVYfuxqw51RB36eOI_nmIxL5azl2izX1U7GMc_zdQr3lyjPIBgf6Fno1bFVvzudeTPzC6ILDuRlRKl1NR0k8b2Gfb4aU2KbUhv1nfhbF3qyWkcsqhF58i0Pz-paQAhUQcavwBgmmpH)

Highlights:

What are Amazon Ads and how do they work
Types of campaigns
Understanding the Ads dashboard
Analyzing & interpreting the metrics
Learn the target CTR, CVR, and ACOS metrics
Optimizing Keywords and Products campaigns
What to do if your ads aren't working
The 3 product page optimizations you must get right to improve conversions

**Comment by ghost** [comment]
Completed.
