### ISSUE TITLE
Competitor Research Analysis - Little Steps Publishing 

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#87]
Email in MR inbox from PubAd Team 02.10.24. Please complete full analysis on the competitor and upload onto the OD. Instructions can be found here: https://github.com/marketing Team > RVM (Rowanvale Marketing) > SMAs > Competitor Research > Analysis Steps.

Please open the 'Process for Analysis' doc and follow the steps, including the other documents mentioned in the instructions.

**Comment by IndieRT** [comment]
Completed 1/11/24
https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7BE06E3043-73BC-4F98-8F0D-6A9EB40E3295%7D&file=Competitor%20Research%20Analysis%20-%20Littlestepspublishing.docx&action=default&mobileredirect=true
