### ISSUE TITLE
Competitor Research Analysis - Bluemoosebooks

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#89]
Email in MR inbox from PubAd Team 09.10.24. Please complete full analysis on the competitor and upload onto the OD. Instructions can be found here: https://github.com/marketing Team > RVM (Rowanvale Marketing) > SMAs > Competitor Research > Analysis Steps.

Please open the 'Process for Analysis' doc and follow the steps, including the other documents mentioned in the instructions.

**Comment by IndieRT** [comment]
Completed 29/10/24
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={03fe29c3-770c-4798-ad90-356ff87733cc}&action=edit
