### ISSUE TITLE
Researching ALLi Editorial Competitors

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#9]
Please look into the ALLi website and complete a list of all of our direct competitors in the Editorial business.

https://www.allianceindependentauthors.org/

**Comment by ghost** [comment]
Completed 14/08/2024
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={ea9d3da4-0d5a-4eed-b247-17f628735057}&action=edit
