### ISSUE TITLE
Competitor Research Analysis - Claretpress

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#90]
Email in MR inbox from PubAd Team 09.10.24. Please complete full analysis on the competitor and upload onto the OD. Instructions can be found here: https://github.com/marketing Team > RVM (Rowanvale Marketing) > SMAs > Competitor Research > Analysis Steps.

Please open the 'Process for Analysis' doc and follow the steps, including the other documents mentioned in the instructions.

**Comment by IndieRT** [comment]
Completed 28/10/24
https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/doc.aspx?sourcedoc={965fbe52-7440-45c8-bf4a-942b1cbf6d1c}&action=edit
