### ISSUE TITLE
Watch Book Marketing Secrets Training and Summarise

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#91]
Watch the training video and make summary notes on a Word Doc - save the summary to the MR Research folder [MR's Research - OneDrive (sharepoint.com)](https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fsarah%5Frowanvalebooks%5Fonmicrosoft%5Fcom%2FDocuments%2F%40%20Marketing%20Team%2FMarketing%20Researchers%2FMR%27s%20Research)

https://www.bmsreplay.com/

**Comment by ghost** [comment]
Completed
