### ISSUE TITLE
Competitor Research Analysis - Miblart

### ISSUE THREAD

**Issue by LucyJonesRV** [LucyJonesRV/Marketing-Researchers#92]
Email in MR inbox from PubAd Team 08.11.24. Please complete full analysis on the competitor and upload onto the OD. Instructions can be found here: https://rowanvalebooks-my.sharepoint.com/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fsarah%5Frowanvalebooks%5Fonmicrosoft%5Fcom%2FDocuments%2F%40%20Marketing%20Team%2FRVM%20%28Rowanvale%20Marketing%29%2FSMAs%2FCompetitor%20Research%2FAnalysis%20Steps
Marketing Team > RVM (Rowanvale Marketing) > SMAs > Competitor Research > Analysis Steps.

Please open the 'Process for Analysis' doc and follow the steps, including the other documents mentioned in the instructions

**Comment by ghost** [comment]
https://rowanvalebooks-my.sharepoint.com/:w:/r/personal/sarah_rowanvalebooks_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7BC912FD98-713D-4C4D-9B9E-6D404CB11545%7D&file=Competitor%20Research%20Analysis%20-%20Miblart.docx&action=default&mobileredirect=true
